import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Docs rewrite baseline: single page (`docs/overview.md`).
// Manual sidebar — do not switch to autogenerated (see documentation/README.md).
// Add new pages deliberately by hand when the rewrite lands.
const sidebars: SidebarsConfig = {
  main: ['overview', 'project-structure', 'agents'],
};

export default sidebars;
